### ISSUE TITLE
Error when extruding "open scad non-zero exit"

### ISSUE THREAD

**Issue by thetrebor** [deffi/svg2stl#2]
Groups:
    black: 760 shapes, max ΔE = 0.00
Rendering to rose_black.stl
Traceback (most recent call last):
  File "/Users/TheTrebor/Projects/svg_extrude/svg_extrude.py", line 118, in <module>
    svg_extrude(parser.parse_args())
  File "/Users/TheTrebor/Projects/svg_extrude/svg_extrude.py", line 89, in svg_extrude
    if args.stl:     render_file(base_name, "stl", scene, args.height, args.overlay, flip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/TheTrebor/Projects/svg_extrude/svg_extrude.py", line 33, in render_file
    with ScadRenderer().render_file(file_name, defines=defines) as scad_file:
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/TheTrebor/Projects/svg_extrude/svg_extrude/scad/renderer.py", line 38, in render_file
    subprocess.run(command, capture_output=True, check=True)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['openscad', '-o', 'rose_black.stl', '-D', 'selection="black"', '/var/folders/lp/4h43w8592_7f59lxw3db7yjr0000gp/T/tmp4u5qh508.scad']' returned non-zero exit status 1.

[tmp4u5qh508.scad.zip](https://github.com/deffi/svg_extrude/files/13734970/tmp4u5qh508.scad.zip)

openscad -o rose_black.stl -D selections="black" tmp4u5qh508.scad                                                 
WARNING: Ignoring unknown variable 'black' in file tmp4u5qh508.scad, line 297676
Geometries in cache: 1515
Geometry cache size in bytes: 72624
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Total rendering time: 0:01:56.668
Current top level object is empty.

not sure what's up.  if this could work it would be exactly what I need

**Comment by thetrebor** [comment]
![rose](https://github.com/deffi/svg_extrude/assets/305910/baf7e67d-02f2-4429-b214-0f5752de472f)
